# Generated by Django 3.2.7 on 2021-09-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkt',
            new_name='Produkty',
        ),
    ]
